// Package main is the entrypoint for the Users API.
//
//	@title			Users API
//	@version		1.0
//	@description	Multi-tenant CRUD API for user management with Redis caching.
//
//	@contact.name	Your Team
//	@contact.email	engineering@yourorg.com
//
//	@license.name	MIT
//
//	@host		localhost:8080
//	@BasePath	/
//
//	@securityDefinitions.apikey	BearerAuth
//	@in							header
//	@name						Authorization
//	@description				JWT Bearer token. Format: "Bearer <token>"
package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/redis/go-redis/v9"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"

	"github.com/adithyvisnu/user-go/config"
	_ "github.com/adithyvisnu/user-go/docs" // generated by `swag init` — DO NOT REMOVE
	"github.com/adithyvisnu/user-go/internal/cache"
	"github.com/adithyvisnu/user-go/internal/handler"
	"github.com/adithyvisnu/user-go/internal/middleware"
	"github.com/adithyvisnu/user-go/internal/models"
	"github.com/adithyvisnu/user-go/internal/repository"
	"github.com/adithyvisnu/user-go/internal/service"
)

func main() {
	// ── Config ────────────────────────────────────────────────────────────────
	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("config: %v", err)
	}

	// ── PostgreSQL ────────────────────────────────────────────────────────────
	gormLogger := logger.Default.LogMode(logger.Info)
	if cfg.Env == "production" {
		gormLogger = logger.Default.LogMode(logger.Warn)
	}

	db, err := gorm.Open(postgres.Open(cfg.DBDSN), &gorm.Config{
		Logger: gormLogger,
	})
	if err != nil {
		log.Fatalf("postgres: %v", err)
	}

	// Connection pool tuning
	sqlDB, _ := db.DB()
	sqlDB.SetMaxOpenConns(25)
	sqlDB.SetMaxIdleConns(5)
	sqlDB.SetConnMaxLifetime(5 * time.Minute)

	// Auto-migrate schema
	if err := db.AutoMigrate(&models.User{}); err != nil {
		log.Fatalf("migrate: %v", err)
	}

	// ── Redis ─────────────────────────────────────────────────────────────────
	rdb := redis.NewClient(&redis.Options{
		Addr:     cfg.RedisAddr,
		Password: cfg.RedisPassword,
		DB:       0,
	})
	if err := rdb.Ping(context.Background()).Err(); err != nil {
		log.Fatalf("redis: %v", err)
	}
	cacheClient := cache.New(rdb)

	// ── Wire dependencies ─────────────────────────────────────────────────────
	userRepo    := repository.NewUserRepository(db, cacheClient)
	userService := service.NewUserService(userRepo)
	userHandler := handler.NewUserHandler(userService)

	// ── Router ────────────────────────────────────────────────────────────────
	if cfg.Env == "production" {
		gin.SetMode(gin.ReleaseMode)
	}

	r := gin.New()
	r.Use(middleware.Recovery())
	r.Use(middleware.RequestLogger())

	// Health check — no auth required
	r.GET("/health", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"status": "ok", "env": cfg.Env})
	})

	// Swagger UI — available at /swagger/index.html
	// Regenerate docs with: swag init -g cmd/api/main.go
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// API v1 — all routes require auth
	v1 := r.Group("/v1")
	v1.Use(middleware.Auth())
	{
		userHandler.RegisterRoutes(v1)
	}

	// ── Server ────────────────────────────────────────────────────────────────
	srv := &http.Server{
		Addr:         fmt.Sprintf(":%s", cfg.Port),
		Handler:      r,
		ReadTimeout:  10 * time.Second,
		WriteTimeout: 30 * time.Second,
		IdleTimeout:  60 * time.Second,
	}

	// Graceful shutdown
	go func() {
		log.Printf("🚀 server listening on :%s  (swagger: http://localhost:%s/swagger/index.html)", cfg.Port, cfg.Port)
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("listen: %v", err)
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	log.Println("shutting down gracefully...")
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	if err := srv.Shutdown(ctx); err != nil {
		log.Fatalf("forced shutdown: %v", err)
	}
	log.Println("server exited")
}
